name: Landon's Jekyll Blog
description: "Landon's Jekyll Blog"
pygments: true
markdown: redcarpet


url: "http://localhost:4000"
baseurl: /jekyllblog

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true
